### PR TITLE
remove recursion to avoid  "Maximum call stack size exceeded" errors

### PR DESCRIPTION
**Pull request by abanchev**
If you have very big trees, sometimes the recursion causes the call stack size to exceed its limit

Converted the calls to use iterative approach instead

### CODE REVIEW

**Comment by abanchev** [comment]
Would be nice if there are tests to make sure all is good

**Comment by eyas-ranjous** [comment]
@abanchev thanks for making these changes. the recursive version of the BST is a kind of the standard one for most of devs, and i would like to keep it around. if you can create a new type of the tree that works without recursion like BinarySearchTreeIterative & AvlTreeIterative, that'd be nice.

**Comment by abanchev** [comment]
@andy0130tw not really, you can publish it if you care to, or you can refactor it with a new name and submit a PR here

**Comment by eyas-ranjous** [comment]
@andy0130tw I can add the implementation here. But not by modifying the existing insert. Can you please open a feature request in the repo. Thanks

**Comment by eyas-ranjous** [comment]
the iterative feature is now available in [v5.4.0](https://github.com/datastructures-js/binary-search-tree/releases/tag/v5.4.0)

Docs: https://datastructures-js.info/docs/binary-search-tree

**Pull request closed without merging**
